version: "3"
services:
  breddit_db:
    image: postgres
    volumes:
      - breddit_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDB}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    networks:
      - breddit_net
    ports:
      - ${PGPORT}:5432

  panel:
    image: adminer
    networks:
      - breddit_net
    ports:
      - ${PANEL_PORT}:8080

networks:
  breddit_net:

volumes:
  breddit_db_data:
